test

diff --git a/start_jupyter b/start_jupyter
--- a/start_jupyter
+++ b/start_jupyter
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 
 # Update Conda environment with runtime dependencies
-echo "Updating Conda environment..."
-conda env update --file runtime.yml || { echo "Conda env update failed"; exit 1; }
+# echo "Updating Conda environment..."
+# conda env update --file runtime.yml || { echo "Conda env update failed"; exit 1; }
 
-# Install additional runtime pip dependencies
-echo "Installing pip dependencies..."
-pip install -r requirements.txt
+# # Install additional runtime pip dependencies
+# echo "Installing pip dependencies..."
+# pip install -r requirements.txt
 
 echo "Starting pgcontents initialization"
 pgcontents init -l $DATABASE_URL --no-prompt || exit 1
